apiVersion: v1
kind: Service
metadata:
  name: misinfo-service
spec:
  selector:
    app: misinformation
  ports:
    - name: backend-port
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30001
    - name: frontend-port
      protocol: TCP
      port: 8501
      targetPort: 8501 
      nodePort: 30002
  type: NodePort